### ISSUE TITLE
Enhancement - Running test from feature file directly on IDE

### ISSUE THREAD

**Issue by zpaya** [shankybnl/MobileAutomationFramework#25]
When directly running Scenario from LoginTest.feature file, then getting below error

```
"C:\Program Files\Java\jdk-16.0.1\bin\java.exe" -Dorg.jetbrains.run.directory=E:\Working\droid\MobileAutomationFramework\src\test\java\tests\cucumberTests\features -javaagent:E:\Software\dev\ideaIC-2021.2.1.win\lib\idea_rt.jar=61892:E:\Software\dev\ideaIC-2021.2.1.win\bin -Dfile.encoding=UTF-8 -classpath E:\Working\droid\MobileAutomationFramework\target\test-classes;E:\Working\droid\MobileAutomationFramework\target\classes;C:\Users\im\.m2\repository\org\projectlombok\lombok\1.18.20\lombok-1.18.20.jar;C:\Users\im\.m2\repository\junit\junit\4.13.1\junit-4.13.1.jar;C:\Users\im\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\im\.m2\repository\org\apache\maven\plugins\maven-surefire-report-plugin\2.19.1\maven-surefire-report-plugin-2.19.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-project\2.2.1\maven-project-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-settings\2.2.1\maven-settings-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-profile\2.2.1\maven-profile-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-artifact-manager\2.2.1\maven-artifact-manager-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-repository-metadata\2.2.1\maven-repository-metadata-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\wagon\wagon-provider-api\1.0-beta-6\wagon-provider-api-1.0-beta-6.jar;C:\Users\im\.m2\repository\backport-util-concurrent\backport-util-concurrent\3.1\backport-util-concurrent-3.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-plugin-registry\2.2.1\maven-plugin-registry-2.2.1.jar;C:\Users\im\.m2\repository\org\codehaus\plexus\plexus-interpolation\1.11\plexus-interpolation-1.11.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-artifact\2.2.1\maven-artifact-2.2.1.jar;C:\Users\im\.m2\repository\org\codehaus\plexus\plexus-container-default\1.0-alpha-9-stable-1\plexus-container-default-1.0-alpha-9-stable-1.jar;C:\Users\im\.m2\repository\classworlds\classworlds\1.1-alpha-2\classworlds-1.1-alpha-2.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-model\2.2.1\maven-model-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\maven-plugin-api\2.2.1\maven-plugin-api-2.2.1.jar;C:\Users\im\.m2\repository\org\apache\maven\plugin-tools\maven-plugin-annotations\3.3\maven-plugin-annotations-3.3.jar;C:\Users\im\.m2\repository\org\apache\maven\surefire\surefire-report-parser\2.19.1\surefire-report-parser-2.19.1.jar;C:\Users\im\.m2\repository\org\apache\maven\reporting\maven-reporting-api\3.0\maven-reporting-api-3.0.jar;C:\Users\im\.m2\repository\org\apache\maven\reporting\maven-reporting-impl\2.4\maven-reporting-impl-2.4.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-core\1.6\doxia-core-1.6.jar;C:\Users\im\.m2\repository\xerces\xercesImpl\2.9.1\xercesImpl-2.9.1.jar;C:\Users\im\.m2\repository\xml-apis\xml-apis\1.3.04\xml-apis-1.3.04.jar;C:\Users\im\.m2\repository\xmlunit\xmlunit\1.5\xmlunit-1.5.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-sink-api\1.6\doxia-sink-api-1.6.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-logging-api\1.6\doxia-logging-api-1.6.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-site-renderer\1.6\doxia-site-renderer-1.6.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-decoration-model\1.6\doxia-decoration-model-1.6.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-module-xhtml\1.6\doxia-module-xhtml-1.6.jar;C:\Users\im\.m2\repository\org\apache\maven\doxia\doxia-module-fml\1.6\doxia-module-fml-1.6.jar;C:\Users\im\.m2\repository\org\codehaus\plexus\plexus-i18n\1.0-beta-7\plexus-i18n-1.0-beta-7.jar;C:\Users\im\.m2\repository\org\codehaus\plexus\plexus-velocity\1.1.7\plexus-velocity-1.1.7.jar;C:\Users\im\.m2\repository\org\apache\velocity\velocity\1.5\velocity-1.5.jar;C:\Users\im\.m2\repository\oro\oro\2.0.8\oro-2.0.8.jar;C:\Users\im\.m2\repository\org\apache\velocity\velocity-tools\2.0\velocity-tools-2.0.jar;C:\Users\im\.m2\repository\commons-chain\commons-chain\1.1\commons-chain-1.1.jar;C:\Users\im\.m2\repository\dom4j\dom4j\1.1\dom4j-1.1.jar;C:\Users\im\.m2\repository\sslext\sslext\1.2-0\sslext-1.2-0.jar;C:\Users\im\.m2\repository\org\apache\struts\struts-core\1.3.8\struts-core-1.3.8.jar;C:\Users\im\.m2\repository\antlr\antlr\2.7.2\antlr-2.7.2.jar;C:\Users\im\.m2\repository\org\apache\struts\struts-taglib\1.3.8\struts-taglib-1.3.8.jar;C:\Users\im\.m2\repository\org\apache\struts\struts-tiles\1.3.8\struts-tiles-1.3.8.jar;C:\Users\im\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\im\.m2\repository\org\codehaus\plexus\plexus-component-annotations\1.5.5\plexus-component-annotations-1.5.5.jar;C:\Users\im\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.15\plexus-utils-3.0.15.jar;C:\Users\im\.m2\repository\org\apache\maven\shared\maven-shared-utils\0.9\maven-shared-utils-0.9.jar;C:\Users\im\.m2\repository\com\google\code\findbugs\jsr305\2.0.1\jsr305-2.0.1.jar;C:\Users\im\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\im\.m2\repository\org\apache\commons\commons-configuration2\2.1.1\commons-configuration2-2.1.1.jar;C:\Users\im\.m2\repository\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\im\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\im\.m2\repository\com\saucelabs\sauce_java_common\2.1.23\sauce_java_common-2.1.23.jar;C:\Users\im\.m2\repository\com\saucelabs\sauce_testng\2.1.23\sauce_testng-2.1.23.jar;C:\Users\im\.m2\repository\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar;C:\Users\im\.m2\repository\com\saucelabs\saucerest\1.0.32\saucerest-1.0.32.jar;C:\Users\im\.m2\repository\org\json\json\20090211\json-20090211.jar;C:\Users\im\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\im\.m2\repository\mysql\mysql-connector-java\8.0.16\mysql-connector-java-8.0.16.jar;C:\Users\im\.m2\repository\com\google\protobuf\protobuf-java\3.6.1\protobuf-java-3.6.1.jar;C:\Users\im\.m2\repository\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\im\.m2\repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;C:\Users\im\.m2\repository\org\apache\httpcomponents\httpcore\4.4\httpcore-4.4.jar;C:\Users\im\.m2\repository\io\appium\java-client\6.1.0\java-client-6.1.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-java\3.12.0\selenium-java-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.12.0\selenium-chrome-driver-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.12.0\selenium-edge-driver-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.12.0\selenium-firefox-driver-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.12.0\selenium-ie-driver-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.12.0\selenium-opera-driver-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.12.0\selenium-remote-driver-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.12.0\selenium-safari-driver-3.12.0.jar;C:\Users\im\.m2\repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3.jar;C:\Users\im\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\im\.m2\repository\com\google\guava\guava\23.6-jre\guava-23.6-jre.jar;C:\Users\im\.m2\repository\org\checkerframework\checker-compat-qual\2.0.0\checker-compat-qual-2.0.0.jar;C:\Users\im\.m2\repository\com\google\errorprone\error_prone_annotations\2.1.3\error_prone_annotations-2.1.3.jar;C:\Users\im\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\im\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\im\.m2\repository\com\squareup\okhttp3\okhttp\3.9.1\okhttp-3.9.1.jar;C:\Users\im\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-support\3.12.0\selenium-support-3.12.0.jar;C:\Users\im\.m2\repository\org\seleniumhq\selenium\selenium-api\3.12.0\selenium-api-3.12.0.jar;C:\Users\im\.m2\repository\com\google\code\gson\gson\2.8.4\gson-2.8.4.jar;C:\Users\im\.m2\repository\cglib\cglib\3.2.6\cglib-3.2.6.jar;C:\Users\im\.m2\repository\org\ow2\asm\asm\6.0\asm-6.0.jar;C:\Users\im\.m2\repository\org\apache\ant\ant\1.9.6\ant-1.9.6.jar;C:\Users\im\.m2\repository\org\apache\ant\ant-launcher\1.9.6\ant-launcher-1.9.6.jar;C:\Users\im\.m2\repository\commons-validator\commons-validator\1.6\commons-validator-1.6.jar;C:\Users\im\.m2\repository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar;C:\Users\im\.m2\repository\commons-digester\commons-digester\1.8.1\commons-digester-1.8.1.jar;C:\Users\im\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\im\.m2\repository\org\springframework\spring-context\5.0.5.RELEASE\spring-context-5.0.5.RELEASE.jar;C:\Users\im\.m2\repository\org\springframework\spring-aop\5.0.5.RELEASE\spring-aop-5.0.5.RELEASE.jar;C:\Users\im\.m2\repository\org\springframework\spring-beans\5.0.5.RELEASE\spring-beans-5.0.5.RELEASE.jar;C:\Users\im\.m2\repository\org\springframework\spring-core\5.0.5.RELEASE\spring-core-5.0.5.RELEASE.jar;C:\Users\im\.m2\repository\org\springframework\spring-jcl\5.0.5.RELEASE\spring-jcl-5.0.5.RELEASE.jar;C:\Users\im\.m2\repository\org\springframework\spring-expression\5.0.5.RELEASE\spring-expression-5.0.5.RELEASE.jar;C:\Users\im\.m2\repository\org\aspectj\aspectjweaver\1.9.1\aspectjweaver-1.9.1.jar;C:\Users\im\.m2\repository\org\openpnp\opencv\3.2.0-1\opencv-3.2.0-1.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-java\1.2.5\cucumber-java-1.2.5.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-core\1.2.5\cucumber-core-1.2.5.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-html\0.2.3\cucumber-html-0.2.3.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-testng\1.2.5\cucumber-testng-1.2.5.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-junit\1.2.5\cucumber-junit-1.2.5.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-picocontainer\1.2.5\cucumber-picocontainer-1.2.5.jar;C:\Users\im\.m2\repository\info\cukes\cucumber-jvm-deps\1.0.5\cucumber-jvm-deps-1.0.5.jar;C:\Users\im\.m2\repository\info\cukes\gherkin\2.12.2\gherkin-2.12.2.jar;C:\Users\im\.m2\repository\org\picocontainer\picocontainer\2.15\picocontainer-2.15.jar;C:\Users\im\.m2\repository\org\testng\testng\7.4.0\testng-7.4.0.jar;C:\Users\im\.m2\repository\com\beust\jcommander\1.78\jcommander-1.78.jar;C:\Users\im\.m2\repository\org\webjars\jquery\3.5.1\jquery-3.5.1.jar;E:\Software\dev\ideaIC-2021.2.1.win\plugins\junit\lib\junit-rt.jar;C:\Users\im\AppData\Roaming\JetBrains\IdeaIC2021.2\plugins\cucumber-java\lib\cucumber-jvmFormatter.jar cucumber.api.cli.Main --plugin org.jetbrains.plugins.cucumber.java.run.CucumberJvmSMFormatter --monochrome --name "^User should be able to login on app with correct credentials and initial set up should be shown$" --glue cucumberIntegrationTests.stepDefinitions.common E:/Working/droid/MobileAutomationFramework/src/test/java/tests/cucumberTests/features/LoginTest.feature
Testing started at 21:55 ...

java.lang.ExceptionInInitializerError
at cucumber.deps.com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
  at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
  at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:530)
  at cucumber.runtime.xstream.LocalizedXStreams$LocalizedXStream.<init>(LocalizedXStreams.java:50)
  at cucumber.runtime.xstream.LocalizedXStreams.newXStream(LocalizedXStreams.java:37)
  at cucumber.runtime.xstream.LocalizedXStreams.get(LocalizedXStreams.java:29)
  at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
  at cucumber.runtime.Runtime.runStep(Runtime.java:300)
  at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
  at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
  at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
  at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
  at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
  at cucumber.runtime.Runtime.run(Runtime.java:122)
  at cucumber.api.cli.Main.run(Main.java:36)
  at cucumber.api.cli.Main.main(Main.java:18)
  at ✽.Given User has slideshare "android" app(E:/Working/droid/MobileAutomationFramework/src/test/java/tests/cucumberTests/features/LoginTest.feature:6)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @4c98385c
  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
  at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
  at cucumber.deps.com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
  at cucumber.deps.com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
  at cucumber.deps.com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
  at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
  at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:530)
  at cucumber.runtime.xstream.LocalizedXStreams$LocalizedXStream.<init>(LocalizedXStreams.java:50)
  at cucumber.runtime.xstream.LocalizedXStreams.newXStream(LocalizedXStreams.java:37)
  at cucumber.runtime.xstream.LocalizedXStreams.get(LocalizedXStreams.java:29)
  at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
  at cucumber.runtime.Runtime.runStep(Runtime.java:300)
  at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
  at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
  at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
  at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
  at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
  at cucumber.runtime.Runtime.run(Runtime.java:122)
  at cucumber.api.cli.Main.run(Main.java:36)
  at cucumber.api.cli.Main.main(Main.java:18)

Skipped step

Skipped step

Skipped step

Skipped step

Skipped step

Skipped step

Failed scenarios:
E:/Working/droid/MobileAutomationFramework/src/test/java/tests/cucumberTests/features/LoginTest.feature:8 # Scenario: User should be able to login on app with correct credentials and initial set up should be shown

1 Scenarios (1 failed)
7 Steps (1 failed, 6 skipped)
0m0.150s

java.lang.ExceptionInInitializerError
	at cucumber.deps.com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
	at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:530)
	at cucumber.runtime.xstream.LocalizedXStreams$LocalizedXStream.<init>(LocalizedXStreams.java:50)
	at cucumber.runtime.xstream.LocalizedXStreams.newXStream(LocalizedXStreams.java:37)
	at cucumber.runtime.xstream.LocalizedXStreams.get(LocalizedXStreams.java:29)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
	at ✽.Given User has slideshare "android" app(E:/Working/droid/MobileAutomationFramework/src/test/java/tests/cucumberTests/features/LoginTest.feature:6)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @4c98385c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at cucumber.deps.com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:39)
	at cucumber.deps.com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
	at cucumber.deps.com.thoughtworks.xstream.XStream.setupConverters(XStream.java:820)
	at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at cucumber.deps.com.thoughtworks.xstream.XStream.<init>(XStream.java:530)
	at cucumber.runtime.xstream.LocalizedXStreams$LocalizedXStream.<init>(LocalizedXStreams.java:50)
	at cucumber.runtime.xstream.LocalizedXStreams.newXStream(LocalizedXStreams.java:37)
	at cucumber.runtime.xstream.LocalizedXStreams.get(LocalizedXStreams.java:29)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:300)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)


Process finished with exit code 1

```

**Comment by zpaya** [comment]
I am trying to fix this...
