### ISSUE TITLE
Configuration Failure

### ISSUE THREAD

**Issue by debasismohanty** [shankybnl/MobileAutomationFramework#5]
While i try to execute the runner class(Run as) using TestNG i found below error. @shankybnl  Can you please guide me on this.

FAILED CONFIGURATION: @BeforeMethod driverObjectCreation
org.testng.TestNGException: 
Parameter 'os' is required by @Configuration on method driverObjectCreation but has not been marked @Optional or defined
in C:\Users\debasismohanty\AppData\Local\Temp\testng-eclipse-2035336871\testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:84)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:201)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED: feature(Verify login functionality of an app)
         Runs Cucumber Feature

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@6a2bcfcb: 40 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@b97c004: 42 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 10 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@548b7f67: 9 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@5056dfcb: 75 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@573f2bb1: 9 ms

**Comment by shankybnl** [comment]
'os' parameter is mandatory. In case you are running a cucumber test from command line, execute below command for android as mentioned in README.md file: 
 
$ cd mobileautomationframework/ 
$ mvn test -Dos=android -Dsurefire.suiteXmlFiles=cucumberTestng.xml

If you are directly running CucumberRunnerUtil.java class then pass 'os' parameter value as 'android or iOS' along with it.
